export const ROUTES = {
  HOME: '/',
  MYPAGE: (id: string) => `/mypage/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  POST: '/post',
  POST_DETAIL: '/post/:id',
  POST_EDIT: '/post/:id/edit',
  FEED: (id: string) => `/feed/${id}`,
  ADD_FEED: (id: string) => `/addfeed/${id}`,
  STAMP: '/stamp',
  STAMP_RANK: '/stamp-rank',
  LIVE: '/live',
  MARKET: '/market',
  ITEM: '/item',
  SEARCH: '/search',
  FESTIVAL: '/festival',
  WALLET: '/stamp-wallet',
  REGION_WALLET: (id: string) => `/stamp-wallet/${id}`,
};
