export const ROUTES = {
  HOME: '/',
  MYPAGE: '/mypage',
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  POST: '/post',
  POST_DETAIL: (id: string) => `/post/${id}`,
  POST_EDIT: (id: string) => `/post/${id}/edit`,
  FEED: '/feed',
  STAMP: '/stamp',
  STAMP_RANK: '/stamp-rank',
  LIVE: '/live',
  SEARCH: '/search',
  FESTIVAL_DETAIL: (id: string) => `/festival/${id}`,
};
