export const ROUTES = {
  HOME: '/',
  MYPAGE: (id: string) => `/mypage/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  POST: '/post',
  POST_DETAIL: '/post/:id',
  POST_EDIT: '/post/:id/edit',
  FEED: '/feed',
  STAMP: '/stamp',
  LIVE: '/live',
  MARKET: '/market',
  ITEM: '/item',
};
